### ISSUE TITLE
::stylefy/mode should support pseudo class rule ordering

### ISSUE THREAD

**Issue by scramjet** [Jarzka/stylefy#40] opened 2019-08-08 01:51 UTC
Hello, I'm using `::stylefy/mode` to add hover and active effects to a button (see example below), and have found the order of the rules matters. If `:active` is not second, then its background does not override `:hover`.

```
::stylefy/mode  {:hover  {:background-color "#ffedcf"}
                           :active {:background-color "blue" :color "white"}}
```

This actually works due to the implementation of small maps in CLJS (the key order is preserved), but isn't guaranteed.

Can I propose that `::stylefy/mode` also accept this syntax?:

```
::stylefy/mode  [[:hover  {:background-color "#ffedcf"}]
                 [:active {:background-color "blue" :color "white"}]]
```

Since `seq` on a map generates key/value pairs, this shouldn't even require much change to the code: just use vector destructuring  rather than `key` and `val`.

Cheers,

Matt.

**Comment by Jarzka** [comment] 2019-08-08 06:40
Hi

Yes, it seems that the order of CSS pseudo classes is important in some cases - link states being a common example of this. I agree that in cases like this we should not rely on the order of CLJS map keys, which usually outputs the CSS as expected, but it is not guaranteed. I believe your proposal of using a vector syntax is a great way to solve this problem. I have been thinking of something like this for media queries too but there has not yet been any case in which I would have needed it. So, maybe we should implement the vector syntax for modes only at this point.

My vacation ends this week. Hopefully I'll have time to implement this next week.

**Comment by scramjet** [comment] 2019-08-08 07:32
Great! Really finding Stylefy useful!

**Comment by Jarzka** [comment] 2019-08-12 16:57
This feature is now implemented in `1.14.0-beta1`. Feel free to test it. If no problems are found, I mark it stable in a week or two.

Here are the changes: https://github.com/Jarzka/stylefy/pull/41/files

**Comment by scramjet** [comment] 2019-08-13 05:55
Hi Jari,

just gave the beta a try, but getting this error:

```
Uncaught TypeError: me.cljs$core$IMapEntry$_key$arity$1 is not a function
    at Object.cljs$core$ISeq$_first$arity$1 (VM15758 core.js:29352)
    at Object.cljs$core$_first [as _first] (VM15758 core.js:1724)
    at Object.cljs$core$first [as first] (VM15758 core.js:4459)
    at VM15758 core.js:19148
    at Object.sval (VM15758 core.js:11499)
    at Object.cljs$core$ISeqable$_seq$arity$1 (VM15758 core.js:11650)
    at Object.cljs$core$_seq [as _seq] (VM15758 core.js:2424)
    at Object.cljs$core$seq [as seq] (VM15758 core.js:4423)
    at cljs$core$empty_QMARK_ (VM15758 core.js:7181)
    at stylefy$impl$styles$style_return_value (VM16015 styles.js:158)
```

That was when testing changing the code in my original example.

The line in `stylefy.impl.styles/style-return-value` that is blowing up seems to be line 112:

```clojure
       contains-modes-not-excluded? (not (empty?
                                          (filter (comp not excluded-modes)
                                                   (keys (:stylefy.core/mode style)))))
```

**Comment by Jarzka** [comment] 2019-08-13 06:20
Ah yes, I forgot to update that part of the codebase. Thanks for testing, I'll create a new version in a couple of days.

**Comment by Jarzka** [comment] 2019-08-15 15:30
Reading the "keys" of vector worked on my machine and I was unable to reproduce the error you got. However, I changed the implementation so that if the modes are written in vector format, we do not use the `keys` function but the the first values of the vector items. This should work correctly.

Can you test this new version: `1.14.0-beta2`

**Comment by scramjet** [comment] 2019-08-15 23:07
Hi Jari,

`1.14.0-beta2` works, thanks!

`(keys [[1 2]])` throws an exception at the REPL in my environment. Different versions of CLJS? (We're on 1.10.520).

**Comment by Jarzka** [comment] 2019-08-16 06:15
I tested this with the examples project included in this repo. It's running `1.9.542`, so yes, the problem could be related to different CLJS versions. Maybe the implementation of `keys` has changed between versions. I'll have to test it and upgrade the CLJS version in the examples project.

Anyway, good to hear that this new version works! I will publish the stable version `1.14.0` probably sometime during the next week.

**Comment by scramjet** [comment] 2019-08-16 06:55
Excellent. Cheers 👍

**Comment by Jarzka** [comment] 2019-08-17 11:39
Since I did not find any problems in my testing, `1.14.0` is now marked as stable and released.

**Closed by Jarzka** 2019-08-17 11:39 UTC
Labels: enhancement
