### ISSUE TITLE
with-classes deprecated

### ISSUE THREAD

**Issue by fwaddle** [Jarzka/stylefy#14] opened 2018-03-21 04:38 UTC
Hi, I'm trying to create set of styles and I really don't want to 'pollute' my code with styles and classes so I really liked that with-classes existed. 
It however is deprecated and I'm not even sure I'm using it correctly.

I was hoping to do something like this:
```
(def active-cell {:stylefy/sub-styles {:typeA {:background-color "white"
                                               ::stylefy/with-classes ["mb-2" "btn" "btn-block"]}
```

And later on:
```
(defn all-cells []
  [:a (use-sub-style active-cell :typeA {:href ....})
    [:h5 "Blah Blah cell"]])
```

So hoping to avoid having to do this:
```
(defn all-cells []
  [:a (use-sub-style active-cell :typeA {:href "....."  :class "mb-2 btn btn-block"})
    [:h5 "Blah Blah cell"]])
```

This is not the best example because I'm already having to do a :href but I have a tonne of other places I don't do anything except classes and inline styles. 

Is there anything I can do to avoid having to use :class ?

**Comment by Jarzka** [comment] 2018-03-21 07:21
**with-classes** was designed to work only with **use-style** options map, like this:
`(use-style my-style {::stylefy/with-classes ["class1 class2"]})`

The parameters of **use-style** are: the style map & an optional options map. In this example, you use the style **my-style** in some component and attach additional class names to it via options map (class1 and class2). You cannot define additional class names inside a style definition. If you did, I believe they are simply ignored. This means that additional class names are always defined per style usage, not per style map.

However, defining a style map with additional class names always attached to it (like you did) is an interesting idea. Might be worth checking if implementing it would make things easier or not. But since it's not currently supported, the last one of your examples is the correct way to attach additional class names.

**Comment by fwaddle** [comment] 2018-03-21 09:14
Thanks for the quick response. 
Actually the helper functions would be ideal here for now, that way I can pass it the requirements of the href and have it wrap both the href and the class.

Even just having the ability to add classes is a massive leap over where I was last week!

Defining a style map with additional classes would be ideal and if I ever learn enough clojure/clojurescript, CSS, etc then I might send you a PR :)

**Comment by fwaddle** [comment] 2018-03-21 23:48
One other thing that's bugging me related to classes is the inability for you to create a class that inherits other classes. 

Something like this would be perfect:
```
(stylefy/class "blah" {:class "col-sm-12 col-md-5 col-lg-5"})

[:div.blah ....]
```

I'm trying to avoid having to have things like this everywhere:
```
[:div.col-sm-12.col-md-5.col-lg-5.standard-background .....]
```
Do you think there is anything in CSS that would prevent us from writing something like that?

**Comment by Jarzka** [comment] 2018-03-22 14:31
**stylefy/class** was implemented only for certain special cases when you want to create custom CSS classes. In most cases, when you use stylefy, there is no need to create custom CSS classes. You just define styles as Clojure maps and stylefy handles all the ugly CSS code behind.

I think that this problem is not related to stylefy at all, but rather than how you handle CSS classes in Hiccup. The same problem, writing a lot of class names everywhere, would occur without using stylefy.

If you see code duplication when using multiple class names, why not simply create a variable which holds all of those classes:
`(def ugly-classes "col-sm-12.col-md-5.col-lg-5.standard-background)"`

Then you can just use all of those classes everywhere easily:
`(:div {:class ugly-classes})"`

If some of the classes are not needed in some place (for example, you don't need the background color), you can create a function which creates the class string based on the given parameters.

**Comment by fwaddle** [comment] 2018-03-23 02:15
So you might be able to tell I'm very new to web development. Infact the app I'm writing can be considered my first attempt at a web app. I'm creating a prototype of an iOS app that I'd previously written. Anyway coming from that side where I have so much control over how my UI code interacts with the rest of my code, I really was hoping to keep my code as clean as my iOS code. 
Stylefy has been a HUGE help in keeping my code as I would like it - so thank you very much for that. 

I think with the changes I sent you to 'with-classes', I'm actually very happy with the way the code looks and feels. So yeah you can ignore my above comments above about the stylefy/class. 
Using the 'with-classes' changes I can do things like:

```
(def fancy-div {:background-colour colours/fancy-colour
                          ::stylefy/with-classes ["d-none col-sm-12 col-md-5 col-lg-5"]}

[:div (use-style fancy-div)
```

I know it seems minor but having my [:div ...] code nice and clean makes it much nicer to verify things are behaving the way I expect. Again it might be purely because I'm just so new to the web dev side of things.

Anyway thank you VERY much for stylefy.

**Comment by Jarzka** [comment] 2018-03-25 14:31
Thanks for using my library. :) It's great to hear that you have picked up ClojureScript and stylefy as your tool of choise even if you are new to web dev.

Your PR is now merged, with a few additional changes (I updated the examples project, tests and doc)

**Closed** 2018-05-06 07:50 UTC
Labels: help wanted
