### ISSUE TITLE
:after & :before pseudo elements don't work

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#19] opened 2018-04-17 14:54 UTC
Firstly thanks for the effort on this library, I'm really enjoying using it.

I've tried `pseudo-elements` with both single and double colon notation and can't get either to work.

### `use-style`
When used on a component I get no `pseudo-element` at all in the browser:
`[:div (use-style {::stylefy/mode {:before {:content "..."}}}) "Foo"]`

![screen shot 2018-04-17 at 15 56 55](https://user-images.githubusercontent.com/1615460/38878074-0ac22ca0-4258-11e8-9a0a-0405e164b7af.png)

### `custom-tag`
When used in a custom tag I see a bad selector but no `pseudo-element`:
`(stylefy/tag "div" {::stylefy/mode {:before {:content "..."}}})`

![screen shot 2018-04-17 at 15 54 27](https://user-images.githubusercontent.com/1615460/38877911-a69515e4-4257-11e8-89e2-8b5ef1fc1c30.png)

**Comment by nijk** [comment] 2018-04-17 14:56
It's worth me mentioning that in an ideal world `pseudo-elements` would be available using the [double colon syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements#Syntax)

**Comment by Jarzka** [comment] 2018-04-17 15:10
Thanks for the bug report.

Personally I'll try to avoid using CSS :before and :after pseudo classes as I often find the difficult to work with. However, bug it is and should be fixed. I can probably take a look at this in a week.

**Comment by nijk** [comment] 2018-04-17 15:15
There are times when they are extremely useful, like in [most clearfix solutions for example](https://github.com/Jarzka/stylefy/blob/f804c11a3c961c457a9aecfe2b44c78e096664b6/examples/src/stylefy/examples/full_page.cljs#L43)

**Comment by Jarzka** [comment] 2018-04-17 15:42
Thanks for testing out my library and giving feedback. I'll try to fix your issues when I have time. :)

By the way, remember that you can always use manually written CSS code on your page as a workaround.

**Comment by nijk** [comment] 2018-04-17 15:44
My pleasure, I've actually just been discussing the option of static css with a colleague as a last resort.

We're embarking on a medium sized green-field project at the moment so I'm keen to get things right from the outset (or as close as possible) to reduce drag on the rest of the project.

**Comment by Jarzka** [comment] 2018-04-20 16:05
After doing a bit of debugging, I believe this not a bug, but incorrect use of :before and :after with stylefy. When you create a style map, the values in the style map are converted to CSS "as they are". Thus, when you do this:
`{::stylefy/mode {:before {:content "yey"}}}`
The output in CSS will be:
`_stylefy_blahblah { content: yey }`

This is incorrect, as the value for content must be in quotes. So:

`{::stylefy/mode {:before {:content "'yey'"}}}`
The output in CSS will be:
`_stylefy_blahblah { content: 'yey' }`

Are you able to get :before and :after working with this instruction? If this works for you, I think it should be mentioned in the README file and docs.

**Comment by nijk** [comment] 2018-04-20 16:24
Ah right! I'll certainly give it a go and I think an example in the docs is a great idea. I'd recommend that you explicitly mention support for both pseudo-classes and pseudo-elements.

**Comment by nijk** [comment] 2018-04-20 22:07
Cool, this is working as described with `use-style`.

This doesn't work when used with `stylefy/tag`, but [you've already addressed that point here](https://github.com/Jarzka/stylefy/issues/20#issuecomment-383150114)

**Comment by Jarzka** [comment] 2018-04-20 22:33
Yep. I believe this issue can now be closed.

**Closed by Jarzka** 2018-04-20 22:33 UTC
Labels: help wanted
