### ISSUE TITLE
Possible issue with refs

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#29] opened 2018-07-24 14:56 UTC
I'm not sure exactly where the issue is here but I'm noticing that when I use a `:ref (fn [element] ...)` as a property of the `attrs` map passed to `use-style` I get lots of downstream issues that blow up my application.

So, this works:

```clojure
[:div {:ref (fn [element]
               (when (and element (not ref))
                 (swap! !state assoc :ref element)))
       :style {:display :flex
               :flex-grow 1
               :flex-shrink 0}}]
```

But this breaks:

```clojure
[:div (use-style {:display :flex
                  :flex-grow 1
                  :flex-shrink 0}
                 {:ref (fn [element]
                          (when (and element (not ref))
                            (swap! !state assoc :ref element)))})
```

Is this a known issue or am I doing something wrong here?

**Comment by Jarzka** [comment] 2018-07-24 15:07
This is not a known issue. I probably have to check myself what's causing the problem here.

Is there a specific need why you are using ref? Just curious, since personally I have never needed it. :)

**Comment by nijk** [comment] 2018-07-24 15:15
Yep, refs are used to get access to the underlying DOM node. In my case I need to obtain the dynamic `clientWidth` & `clientHeight` values from the DOM node in order to calculate the size of another component.

**Comment by nijk** [comment] 2018-07-24 15:34
It might also be worth reading this: https://github.com/reagent-project/reagent/blob/master/doc/FAQ/UsingRefs.md

**Comment by Jarzka** [comment] 2018-07-24 15:39
It is possible get access to the component's node in lifecycle method by calling `(r/dom-node this).` Here is an example: https://github.com/solita/solita-rooms/blob/3e86dc65808a7f8e4526db94f9eff956dcd5a9c1/frontend/src/cljs/rooms/ui/input.cljs#L57

**Comment by nijk** [comment] 2018-07-24 15:43
Right, so because of that you won't be supporting refs then?

**Comment by nijk** [comment] 2018-07-24 15:55
It also means that if you have some hiccup within your component, that needs to be broken out to a form-3 just to get the dom node. This really does suck as a workaround

**Comment by Jarzka** [comment] 2018-07-24 15:59
Yes, it's true that this method requires a form-3 component.

I didn't say that I'm not going to support ref, I just haven't used with stylefy before. I'll take a look at it at some point, hopefully at the weekend.

**Comment by nijk** [comment] 2018-07-24 16:00
Ok, thanks. Sorry for the frustrated tone, you've been very responsive in your replies but this is a bit of a show-stopper for me.

**Comment by Jarzka** [comment] 2018-07-24 16:30
I managed to have time to quickly take a look at this. I wrote this and I think it works as expected:

```
(defn ref-example []
  (let [node (r/atom nil)]
    (fn []
      [:div
       (use-style {:color "red"}
                  {:ref (fn [e]
                          (when-not @node
                            (reset! node e)))})
       (str "Just a simple component, and it's node:" (when @node
                                                        @node))])))
```

Can you provide me a minimum example which works incorrectly?

**Comment by nijk** [comment] 2018-07-25 07:34
Thanks, I must have an issue somewhere else then. It's a strange one as the error is only triggered when I pass a ref to stylefy. I'll try to isolate the issue further so see if there's anything useful I can share.

**Comment by Jarzka** [comment] 2018-07-26 11:41
Good to know that you found the cause for this issue. However, I would still like to see some code which shows the incorrect behavior, if you can share some.

stylefy updates the DOM's style tag asynchronously as needed, just like Reagent/React updates the DOM so that the elements in the DOM always match the state of the component. I cannot think many problems that I have had with automatic re-rendering / DOM updates. Thus, I wonder what kind of callback are you waiting if stylefy's automatic DOM update is the reason for it to break?

**Comment by Jarzka** [comment] 2018-08-09 18:43
Can we close this issue?

**Comment by nijk** [comment] 2018-08-09 21:50
Yes please do close the issue

**Closed** 2018-08-10 07:57 UTC
